### ISSUE TITLE
error if nothing happens

### ISSUE THREAD

**Issue by TheOtherOne** [gfrd/egfrd#10]
When only one particle is present in the system with D=0, then the next event time is infinite. This crashes the simulation:
File "/storage1/bossen/devel/egfrd/egfrd.py", line 688, in fire_single
    assert abs(single.dt + single.last_time - self.t) <= 1e-18 \* self.t
AssertionError

We need to fix it

**Comment by TheOtherOne** [comment]
temp fix is obviously to just use very small (but nonzero) D.

**Comment by Jintram** [comment]
0 =< single.dt =< inf
0 =< single.last_time =< self.t
0 =< self.t < inf 

For

```
assert abs(single.dt + single.last_time - self.t) <= 1e-18 * self.t
```

to be correct, if single.dt = inf, either single.last_time should be -inf or self.t should be inf

Normally something is wrong when above code line gives false. But there is no known case where this happens right?

For now, we can assume:

```
assert ((abs(single.dt + single.last_time - self.t) <= 1e-18 * self.t) or (single.dt == numpy.inf))
```

solves this bug right? 

Prettier would of course be to just make the algorithm in such a way this would automatically goes correct. But neither last_time nor self.t will ever be (-)inf..

**Comment by Jintram** [comment]
Pushed fix ( https://github.com/gfrd/egfrd/commit/c79573fbd5ef292e781f36a0a912a75d909429d50 )

**Comment by Jintram** [comment]
Crap..  Sorry, pushed to fast.

```
Traceback (most recent call last):
  File "onestationary.py", line 49, in <module>
    s.step()
  File "../../egfrd.py", line 296, in step
    f(self, event.data)
  File "../../egfrd.py", line 728, in fire_single
    self.fire_single_reaction(single)
  File "../../egfrd.py", line 563, in fire_single_reaction
    rt = single.draw_reaction_rule()
  File "../../single.py", line 147, in draw_reaction_rule
    k_max = k_array[-1]
IndexError: index out of bounds
```

**Comment by Jintram** [comment]
The point thus is: firing goes wrong when dt == inf.

Is this where it goes wrong? -:

```
    # Handle immobile case first.
    if single.getD() == 0:
        # no propagation, just calculate next reaction time.
        single.dt, single.event_type = single.determine_next_event() 
        single.last_time = self.t
        self.add_single_event(single)
        return
```

and:

```
def determine_next_event(self):
    """Return an (event time, event type)-tuple.

    """
    return min(self.draw_escape_or_interaction_time_tuple(),
               self.draw_reaction_time_tuple())
```

draw_reaction_time_tuple() will return inf:

```
def draw_reaction_time_tuple(self):
    """Return a (reaction time, event type)-tuple.

    """
    if self.k_tot == 0:
        dt = numpy.inf
    elif self.k_tot == numpy.inf:
        dt = 0.0
    else:
        dt = (1.0 / self.k_tot) * math.log(1.0 / myrandom.uniform())
    return dt, EventType.SINGLE_REACTION
```

As will draw_escape_or_interaction_time_tuple:

```
def draw_escape_or_interaction_time_tuple(self):
    """Return an (escape or interaction time, event type)-tuple.

    Handles also all interaction events.

    """
    if self.getD() == 0:
        dt = numpy.inf
    else:
        dt = draw_time_wrapper(self.greens_function())

    event_type = EventType.SINGLE_ESCAPE
    return dt, event_type
```

So I guess an event that never happens is then randomly chosen and firing of it is attempted, but obviously fails..

**Comment by Jintram** [comment]
# Conclusion*: 

There should be an eventType "NOTHING" which handles cases like this. Then if such an event is fired, it should just return immediately it's input again.  Perhaps "NOTHING" events should just be removed from the scheduler, otherwise one could get stuck in an infinite loop. And if the scheduler is empty, what should step() then do? 
In addition to this, there is a check somewhere to check if a single is reset, which if above is implemented the script will crash upon.

*) Mmm, this is not very straightforward..

**Comment by thomie** [comment]
How about starting fire_single with:

```
if single.dt == numpy.inf:
    return single 
```

Then it will exit with 

```
RuntimeError: Zero particles left
```

, and a simulator time of infinity. What more do you want the simulator to do in this case?

**Comment by Jintram** [comment]
Yes exactly, that'd be good.

Now I only need to go through the code to understand what exactly happens when you do this..

Btw, better perhaps is:

```
                raise RuntimeError('Zero events left.')
```

:)

**Comment by Jintram** [comment]
And for this very specific case, it's not too bad users should check specifically in their simulation for the next event to lay in infinity.

E.g.

```
if (s.scheduler.size == 0):
    print "Simulation has reached it's final state."
```
