### ISSUE TITLE
eGFRD Crash?

### ISSUE THREAD

**Issue by Jintram** [gfrd/egfrd#13]
I've tried running my rebind sample a load of times, it made eGFRD crash after 4930 runs. But the problem doesn't seem to come from my sample code..
###### Run 4931.

Traceback (most recent call last):
  File "run.py", line 315, in <module>
    int(sys.argv[2]), T_list, int(sys.argv[4]))
  File "run.py", line 78, in run
    r_list, t_list = singlerun(T_list, N_B, N_X)
  File "run.py", line 195, in singlerun
    dd = s.clear_volume(A_pos, float(A['radius'])) # returns a list of 
  File "/storage1/wehrens/myfork_egfrd/egfrd.py", line 530, in clear_volume
    return self.burst_objs(neighbors)
  File "/storage1/wehrens/myfork_egfrd/egfrd.py", line 522, in burst_objs
    b = self.burst_obj(obj)
  File "/storage1/wehrens/myfork_egfrd/egfrd.py", line 499, in burst_obj
    obj = self.burst_single(obj)
  File "/storage1/wehrens/myfork_egfrd/egfrd.py", line 1018, in burst_single
    newsingle = self.propagate_single(single)
  File "/storage1/wehrens/myfork_egfrd/egfrd.py", line 672, in propagate_single
    newpos = single.draw_new_position(single.dt, single.event_type) 
  File "/storage1/wehrens/myfork_egfrd/single.py", line 194, in draw_new_position
    r = draw_r_wrapper(gf, dt, self.get_mobility_radius())
  File "/storage1/wehrens/myfork_egfrd/greens_function_wrapper.py", line 52, in draw_r_wrapper
    (str(e), rnd, dt, gf.dump()))
AttributeError: 'GreensFunction3DAbsSym' object has no attribute 'dump'

**Comment by TheOtherOne** [comment]
Hmmm, klinkt wel duidelijk toch?
'GreensFunction3DAbsSym' object has no attribute 'dump'
klopt dit of kletst hij echt uit z'n nek? De rest is alleen maar traceback, right?

Groetjes,

Laurens

-----Original message-----
To: Laurens Bossen bossen@amolf.nl; 
From:   Jintram reply@reply.github.com
Sent:   Tue 17-05-2011 11:02
Subject:    [egfrd] eGFRD Crash? (#13)

**Comment by TheOtherOne** [comment]
Hmmm, just found out that this is in any case bad -> drawR apparently failed and an exception is thrown (unsucessfully)...
Nu ook convergentieproblemen in 3DAbsSym? Heel fijn..

grz,

Laurens

-----Original message-----
To: Laurens Bossen bossen@amolf.nl; 
From:   Jintram reply@reply.github.com
Sent:   Tue 17-05-2011 11:02
Subject:    [egfrd] eGFRD Crash? (#13)

**Comment by TheJoris** [comment]
Dump attribute added to GF3DAbsSym.hpp/cpp and the wrapper. This was missing.
