### ISSUE TITLE
Setting LOGLEVEL leads to crash (<-> #83)

### ISSUE THREAD

**Issue by Jintram** [gfrd/egfrd#87]
Additional to issue #83, also setting the LOGLEVEL now doesn't work any more.

```
$ export LOGLEVEL=DEBUG
$ ./simple.py 
Traceback (most recent call last):
  File "./simple.py", line 12, in <module>
    from egfrd import *
  File "/home/jintram/jintram_jul2012_egfrd/egfrd.py", line 31, in <module>
    from gfrdbase import *
  File "/home/jintram/jintram_jul2012_egfrd/gfrdbase.py", line 71, in <module>
    setup_logging()
  File "/home/jintram/jintram_jul2012_egfrd/gfrdbase.py", line 63, in setup_logging
    handler.logger.manager.level = _gfrd.CppLoggerHandler.translateLevelValue(levelvalue)
AttributeError: type object 'CppLoggerHandler' has no attribute 'translateLevelValue'
```

**Comment by Jintram** [comment]
This issue concerns using Python 2.7, when using Python 2.6 there appear to be no problems. 

Also, when compiling using Python 2.7, there don't seem to be any complaints about the logger, we only have a different warning concerning the logger:

```

$ grep ogger compiler_output.log | grep warning
PythonAppender.cpp:48:75: warning: passing NULL to non-pointer argument 6 of 'typename boost::python::detail::dependent<boost::python::api::object, A0>::type boost::python::api::object_operators<U>::operator()(const A0&, const A1&, const A2&, const A3&, const A4&, const A5&, const A6&, const A7&) const [with A0 = const char*, A1 = Logger::level, A2 = char [1], A3 = int, A4 = const char*, A5 = int, A6 = int, A7 = int, U = boost::python::api::object, typename boost::python::detail::dependent<boost::python::api::object, A0>::type = boost::python::api::object]' [-Wconversion-null]
PythonAppender.cpp:48:75: warning: passing NULL to non-pointer argument 6 of 'typename boost::python::detail::dependent<boost::python::api::object, A0>::type boost::python::api::object_operators<U>::operator()(const A0&, const A1&, const A2&, const A3&, const A4&, const A5&, const A6&, const A7&) const [with A0 = const char*, A1 = Logger::level, A2 = char [1], A3 = int, A4 = const char*, A5 = int, A6 = int, A7 = int, U = boost::python::api::object, typename boost::python::detail::dependent<boost::python::api::object, A0>::type = boost::python::api::object]' [-Wconversion-null]
PythonAppender.cpp:48:75: warning: passing NULL to non-pointer argument 7 of 'typename boost::python::detail::dependent<boost::python::api::object, A0>::type boost::python::api::object_operators<U>::operator()(const A0&, const A1&, const A2&, const A3&, const A4&, const A5&, const A6&, const A7&) const [with A0 = const char*, A1 = Logger::level, A2 = char [1], A3 = int, A4 = const char*, A5 = int, A6 = int, A7 = int, U = boost::python::api::object, typename boost::python::detail::dependent<boost::python::api::object, A0>::type = boost::python::api::object]' [-Wconversion-null]
PythonAppender.cpp:48:75: warning: passing NULL to non-pointer argument 7 of 'typename boost::python::detail::dependent<boost::python::api::object, A0>::type boost::python::api::object_operators<U>::operator()(const A0&, const A1&, const A2&, const A3&, const A4&, const A5&, const A6&, const A7&) const [with A0 = const char*, A1 = Logger::level, A2 = char [1], A3 = int, A4 = const char*, A5 = int, A6 = int, A7 = int, U = boost::python::api::object, typename boost::python::detail::dependent<boost::python::api::object, A0>::type = boost::python::api::object]' [-Wconversion-null]
PythonAppender.cpp:48:75: warning: passing NULL to non-pointer argument 8 of 'typename boost::python::detail::dependent<boost::python::api::object, A0>::type boost::python::api::object_operators<U>::operator()(const A0&, const A1&, const A2&, const A3&, const A4&, const A5&, const A6&, const A7&) const [with A0 = const char*, A1 = Logger::level, A2 = char [1], A3 = int, A4 = const char*, A5 = int, A6 = int, A7 = int, U = boost::python::api::object, typename boost::python::detail::dependent<boost::python::api::object, A0>::type = boost::python::api::object]' [-Wconversion-null]
PythonAppender.cpp:48:75: warning: passing NULL to non-pointer argument 8 of 'typename boost::python::detail::dependent<boost::python::api::object, A0>::type boost::python::api::object_operators<U>::operator()(const A0&, const A1&, const A2&, const A3&, const A4&, const A5&, const A6&, const A7&) const [with A0 = const char*, A1 = Logger::level, A2 = char [1], A3 = int, A4 = const char*, A5 = int, A6 = int, A7 = int, U = boost::python::api::object, typename boost::python::detail::dependent<boost::python::api::object, A0>::type = boost::python::api::object]' [-Wconversion-null]
```
